site_name: GenGen
site_url: http://gengen.openbioinformatics.org/
repo_url: http://github.com/WangGenomicsLab/GenGen/
repo_name: GitHub
site_description: GenGen software distribution site
site_author: Kai Wang
site_favicon: favicon.ico
copyright: 2007-2015 GenGen
google_analytics: ['UA-7565705-1', 'gengen.openbioinformatics.org']

docs_dir: docs
include_search: true
#use_absolute_urls: true
#use_directory_urls: false

nav:
- GenGen: index.md

- User Guide
  - Download GenGen: user-guide/download.md
  - Install GenGen: user-guide/install.md

- Tutorial
  - GWAS analysis: tutorial/association.md
  - Pathway analysis: tutorial/pathway.md
  - Allele coding conversion: tutorial/coding.md
  - Imputation helper: tutorial/imputation.md
  - LD-based SNP selection: tutorial/findld.md
  - Scan genomic feature: tutorial/scan.md

- Misc
  - FAQ: misc/faq.md
  - How to contribute: misc/contributing.md
  - Version history: misc/version.md
